version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ACTGRP
  - Aldon
  - autoplay
  - cicd
  - clle
  - configurability
  - CPYTOSTMF
  - CRTDIR
  - CRTRPGMOD
  - CRTSRVPGM
  - CURLIB
  - dashboarding
  - dataq
  - distro
  - DSPSIZ
  - elasticlunr
  - endcols
  - endcolumns
  - enddd
  - enddl
  - enddt
  - ENDPGMEXP
  - endwrap
  - Gitbash
  - greenscreen
  - ILEDOCS
  - jweirich
  - keychain
  - kornshell
  - millisecs
  - miworkplace
  - nodebugio
  - ODBC
  - PGMLVL
  - pkgs
  - PRINTTHIS
  - QCLLESRC
  - QDDSSRC
  - QPRINT
  - QPRPGLESRC
  - QRPGLESRC
  - QSRVSRC
  - QSYS
  - randomart
  - RELATIVEPATH
  - RPGINC
  - Ryver
  - Seeberger
  - serveraddress
  - SRCSTMF
  - SRVPGM
  - STRPGMEXP
  - STRSEU
  - tailwindcss
  - templating
  - weirich
  - WRKMBRPDM
  - WRKUSRPRF
ignoreWords:
  - QPTYPESRC
  - RPGLEINC
  - varchar
  - RPGLE
  - srcstmt
import: []
