version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ACTGRP
  - Aldon
  - ALLOBJ
  - autoplay
  - Bekah
  - Blockquotes
  - bnddir
  - BNDUTIL
  - CCSID
  - chgvar
  - cicd
  - clle
  - clpgm
  - CLRLIB
  - configurability
  - confluentinc
  - CPYTOSTMF
  - CRTBNDCL
  - CRTDIR
  - CRTDSPF
  - CRTDTAQ
  - CRTLIB
  - CRTRPGMOD
  - CRTSRVPGM
  - cssmin
  - CURLIB
  - dashboarding
  - dataq
  - dataqlib
  - dftactgrp
  - distro
  - dribbble
  - DSPF
  - dspfd
  - DSPSIZ
  - DSPSYSVAL
  - DTAARA
  - DTAQ
  - elasticlunr
  - endbq
  - endcols
  - endcolumns
  - enddd
  - enddl
  - enddo
  - enddt
  - endpgm
  - ENDPGMEXP
  - endraw
  - ENDSSH
  - endwrap
  - esac
  - evfevent
  - exfmt
  - extpgm
  - FKEYS
  - Gitbash
  - greenscreen
  - IBMI
  - ILEDOCS
  - inlr
  - Iola
  - iproj
  - isql
  - jweirich
  - keychain
  - keyscan
  - Kjjhaej
  - kornshell
  - LIBL
  - luxon
  - macdougall
  - makei
  - MAXLEN
  - millisecs
  - miworkplace
  - MYCL
  - MYDSPF
  - MYDTAQ
  - MYFIRSTCL
  - MYFIRSTPGM
  - MYOBJLIB
  - MYRPGLE
  - Nelnet
  - nodebugio
  - objlib
  - ODBC
  - PGMLVL
  - piedpiper
  - pinterest
  - pixabay
  - pkgs
  - postslist
  - postslistblocks
  - postslistcards
  - postslistthumbs
  - precompiler
  - PRINTTHIS
  - Proto
  - QCCSID
  - QCLLESRC
  - QDDSSRC
  - QDTASRC
  - QPRINT
  - QPRPGLESRC
  - QRPGLESRC
  - QSNDDTAQ
  - QSRVSRC
  - QSYS
  - randomart
  - RELATIVEPATH
  - RPGINC
  - rpglint
  - Ryver
  - SASL
  - SAVF
  - Seeberger
  - serveraddress
  - Shortcode
  - Shortcodes
  - SJYRHA
  - socialshare
  - SQLRPGLE
  - sqltype
  - SRCSTMF
  - SRVPGM
  - Streamfile
  - streamfiles
  - STRPGMEXP
  - STRSEU
  - SUBDIRS
  - tablename
  - tailwindcss
  - templating
  - ubb
  - unixodbc
  - USERID
  - Usrlibl
  - VARBINARY
  - vratio
  - vstart
  - vtitle
  - weirich
  - workstn
  - WRKMBRPDM
  - WRKUSRPRF
  - zookeeeper
ignoreWords:
  - QPTYPESRC
  - RPGLEINC
  - varchar
  - RPGLE
  - srcstmt
import: []
