version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ACTGRP
  - ADDENVVAR
  - Aldon
  - ALLOBJ
  - autoplay
  - awardable
  - Bekah
  - Blockquotes
  - bnddir
  - BNDUTIL
  - CCSID
  - chgvar
  - cicd
  - clle
  - CLOB
  - clpgm
  - CLRLIB
  - CMDLINE
  - configurability
  - confluentinc
  - CPYTOSTMF
  - CRTBNDCL
  - CRTDIR
  - CRTDSPF
  - CRTDTAQ
  - CRTLIB
  - CRTRPGMOD
  - CRTSRVPGM
  - cssmin
  - CURLIB
  - dashboarding
  - dataq
  - dataqlib
  - dftactgrp
  - distro
  - dribbble
  - DSPF
  - dspfd
  - DSPSIZ
  - DSPSTDOUT
  - DSPSYSVAL
  - DTAARA
  - DTAQ
  - elasticlunr
  - endbq
  - endcols
  - endcolumns
  - enddd
  - enddl
  - enddo
  - enddt
  - endpgm
  - ENDPGMEXP
  - endraw
  - ENDSSH
  - endwrap
  - esac
  - evfevent
  - exfmt
  - extpgm
  - FKEYS
  - Gitbash
  - glpat
  - greenscreen
  - HTTPAPI
  - HTTPBLOB
  - HTTPBLOBVERBOSE
  - HTTPCLOB
  - HTTPCLOBVERBOSE
  - HTTPDELETEBLOB
  - HTTPDELETEBLOBVERBOSE
  - HTTPDELETECLOB
  - HTTPDELETECLOBVERBOSE
  - HTTPGETBLOB
  - HTTPGETBLOBVERBOSE
  - HTTPGETCLOB
  - HTTPGETCLOBVERBOSE
  - HTTPHEAD
  - HTTPPOSTBLOB
  - HTTPPOSTBLOBVERBOSE
  - HTTPPOSTCLOB
  - HTTPPOSTCLOBVERBOSE
  - HTTPPUTBLOB
  - HTTPPUTBLOBVERBOSE
  - HTTPPUTCLOB
  - HTTPPUTCLOBVERBOSE
  - IBMI
  - ICSS
  - ILEDOCS
  - inlr
  - Iola
  - iproj
  - isql
  - jdubbtx
  - jweirich
  - keychain
  - keyscan
  - Kjjhaej
  - Klement's
  - kornshell
  - LIBL
  - luxon
  - macdougall
  - makei
  - MAXLEN
  - millisecs
  - miworkplace
  - MYCL
  - MYDSPF
  - MYDTAQ
  - MYFIRSTCL
  - MYFIRSTPGM
  - MYOBJLIB
  - MYRPGLE
  - Nelnet
  - nodebugio
  - objlib
  - ODBC
  - Oni's
  - openyouri
  - PGMLVL
  - piedpiper
  - pinterest
  - pixabay
  - pkgs
  - postslist
  - postslistblocks
  - postslistcards
  - postslistthumbs
  - precompiler
  - PRINTTHIS
  - Proto
  - QCCSID
  - QCLLESRC
  - QDDSSRC
  - QDTASRC
  - QIBM
  - QPRINT
  - QPRPGLESRC
  - QRPGLESRC
  - QSHCURL
  - QSHONI
  - QSNDDTAQ
  - QSRVSRC
  - QSYS
  - randomart
  - RELATIVEPATH
  - RPGINC
  - rpglint
  - Ryver
  - SASL
  - SAVF
  - Schoen's
  - Seeberger
  - serveraddress
  - Shortcode
  - Shortcodes
  - SJYRHA
  - socialshare
  - SQLRPGLE
  - sqltype
  - SRCSTMF
  - SRVPGM
  - Streamfile
  - streamfiles
  - STRPGMEXP
  - STRSEU
  - SUBDIRS
  - SYSTOOL
  - SYSTOOLS
  - tablename
  - tailwindcss
  - templating
  - ubb
  - unixodbc
  - URLDECODE
  - URLENCODE
  - USERDATA
  - USERID
  - Usrlibl
  - VARBINARY
  - vratio
  - vstart
  - vtitle
  - weirich
  - workstn
  - WRKMBRPDM
  - WRKUSRPRF
  - zookeeeper
ignoreWords:
  - QPTYPESRC
  - RPGLEINC
  - varchar
  - RPGLE
  - srcstmt
import: []
