version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ACTGRP
  - autoplay
  - configurability
  - CRTRPGMOD
  - CRTSRVPGM
  - CURLIB
  - dashboarding
  - distro
  - elasticlunr
  - endcols
  - endcolumns
  - enddd
  - enddl
  - enddt
  - ENDPGMEXP
  - endwrap
  - greenscreen
  - ILEDOCS
  - jweirich
  - millisecs
  - miworkplace
  - ODBC
  - PGMLVL
  - PRINTTHIS
  - QPRINT
  - QPRPGLESRC
  - QSRVSRC
  - RELATIVEPATH
  - RPGINC
  - Seeberger
  - SRCSTMF
  - SRVPGM
  - STRPGMEXP
  - STRSEU
  - templating
  - weirich
  - WRKMBRPDM
ignoreWords:
  - QPTYPESRC
  - RPGLEINC
  - varchar
  - RPGLE
  - srcstmt
import: []
