version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ACTGRP
  - Aldon
  - autoplay
  - bnddir
  - BNDUTIL
  - CCSID
  - chgvar
  - cicd
  - clle
  - clpgm
  - configurability
  - confluentinc
  - CPYTOSTMF
  - CRTBNDCL
  - CRTDIR
  - CRTDSPF
  - CRTDTAQ
  - CRTRPGMOD
  - CRTSRVPGM
  - CURLIB
  - dashboarding
  - dataq
  - dataqlib
  - dftactgrp
  - distro
  - DSPF
  - DSPSIZ
  - DTAARA
  - DTAQ
  - elasticlunr
  - endcols
  - endcolumns
  - enddd
  - enddl
  - enddo
  - enddt
  - endpgm
  - ENDPGMEXP
  - endwrap
  - evfevent
  - exfmt
  - extpgm
  - FKEYS
  - Gitbash
  - greenscreen
  - ILEDOCS
  - inlr
  - iproj
  - isql
  - jweirich
  - keychain
  - Kjjhaej
  - kornshell
  - LIBL
  - MAXLEN
  - millisecs
  - miworkplace
  - MYCL
  - MYDSPF
  - MYDTAQ
  - MYFIRSTCL
  - MYFIRSTPGM
  - MYOBJLIB
  - MYRPGLE
  - nodebugio
  - objlib
  - ODBC
  - PGMLVL
  - pkgs
  - precompiler
  - PRINTTHIS
  - Proto
  - QCCSID
  - QCLLESRC
  - QDDSSRC
  - QDTASRC
  - QPRINT
  - QPRPGLESRC
  - QRPGLESRC
  - QSNDDTAQ
  - QSRVSRC
  - QSYS
  - randomart
  - RELATIVEPATH
  - RPGINC
  - rpglint
  - Ryver
  - SASL
  - Seeberger
  - serveraddress
  - SQLRPGLE
  - sqltype
  - SRCSTMF
  - SRVPGM
  - STRPGMEXP
  - STRSEU
  - SUBDIRS
  - tablename
  - tailwindcss
  - templating
  - unixodbc
  - Usrlibl
  - VARBINARY
  - weirich
  - workstn
  - WRKMBRPDM
  - WRKUSRPRF
  - zookeeeper
ignoreWords:
  - QPTYPESRC
  - RPGLEINC
  - varchar
  - RPGLE
  - srcstmt
import: []
