image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - _site

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/netlify-cli:latest
  script:
    - netlify deploy --dir=_site --prod --message="Deployed from GitLab CI"
  only:
    - main